// The Rule Forge — composable rule modifiers. Importing this module registers
// every modifier into the engine's MODS registry (engine consults state.rules).
import { MODS, onBoard, sq, findKing } from './engine.js';

const AROUND = [[1, 0], [1, 1], [0, 1], [-1, 1], [-1, 0], [-1, -1], [0, -1], [1, -1]];

export const CATALOG = [
  {
    id: 'royal-knights',
    name: 'Royal Knights',
    emoji: '♞',
    description: 'Knights may also move & capture one square in any direction, like a king.',
  },
  {
    id: 'berserker-pawns',
    name: 'Berserker Pawns',
    emoji: '⚔',
    description: 'Pawns may also capture straight ahead — no more hiding face to face.',
  },
  {
    id: 'wormholes',
    name: 'Wormholes',
    emoji: '🌀',
    description: 'd4↔e5 and e4↔d5 are portals: land on one, teleport to its pair (if empty). Kings included.',
  },
  {
    id: 'atomic-captures',
    name: 'Atomic Captures',
    emoji: '💥',
    description: 'Captures detonate: non-pawn pieces on adjacent squares are destroyed. Vaporize the enemy king to win — just not your own.',
  },
  {
    id: 'king-dash',
    name: 'King Dash',
    emoji: '⚡',
    description: 'The king may also dash two squares in a straight or diagonal line over an empty square.',
  },
];

function stepInto(state, r, c, color, dr, dc) {
  const nr = r + dr, nc = c + dc;
  if (!onBoard(nr, nc)) return null;
  const target = state.board[nr][nc];
  if (target && target.color === color) return null;
  return { from: { r, c }, to: { r: nr, c: nc }, capture: !!target };
}

MODS['royal-knights'] = {
  extraMoves(state, r, c, piece) {
    if (piece.type !== 'n') return [];
    const out = [];
    for (const [dr, dc] of AROUND) {
      const m = stepInto(state, r, c, piece.color, dr, dc);
      if (m) out.push(m);
    }
    return out;
  },
};

MODS['berserker-pawns'] = {
  extraMoves(state, r, c, piece, mode) {
    if (piece.type !== 'p') return [];
    const dir = piece.color === 'w' ? 1 : -1;
    const promoRank = piece.color === 'w' ? 7 : 0;
    const nr = r + dir;
    if (!onBoard(nr, c)) return [];
    const target = state.board[nr][c];
    // In attack mode the square ahead is always threatened; in move mode the
    // forward capture exists only when an enemy stands there (the plain
    // forward push is already generated by the base engine).
    if (mode === 'attacks' || (target && target.color !== piece.color)) {
      const m = { from: { r, c }, to: { r: nr, c }, capture: true };
      if (nr === promoRank) m.promotion = true;
      return [m];
    }
    return [];
  },
};

MODS['king-dash'] = {
  extraMoves(state, r, c, piece) {
    if (piece.type !== 'k') return [];
    const out = [];
    for (const [dr, dc] of AROUND) {
      const midR = r + dr, midC = c + dc;
      if (!onBoard(midR, midC) || state.board[midR][midC]) continue; // dash leaps an EMPTY square
      const m = stepInto(state, r, c, piece.color, 2 * dr, 2 * dc);
      if (m) out.push(m);
    }
    return out;
  },
};
