// The Rule Forge — composable rule modifiers. Importing this module registers
// every modifier into the engine's MODS registry (engine consults state.rules).
import { MODS, onBoard, sq, coords } from './engine.js';

const AROUND = [[1, 0], [1, 1], [0, 1], [-1, 1], [-1, 0], [-1, -1], [0, -1], [1, -1]];

export const CATALOG = [
  {
    id: 'royal-knights',
    name: 'Royal Knights',
    emoji: '♞',
    description: 'Knights may also move & capture one square in any direction, like a king.',
  },
  {
    id: 'berserker-pawns',
    name: 'Berserker Pawns',
    emoji: '⚔',
    description: 'Pawns may also capture straight ahead — no more hiding face to face.',
  },
  {
    id: 'wormholes',
    name: 'Wormholes',
    emoji: '🌀',
    description: 'd4↔e5 and e4↔d5 are portals: land on one, teleport to its pair (if empty). Kings included.',
  },
  {
    id: 'atomic-captures',
    name: 'Atomic Captures',
    emoji: '💥',
    description: 'Captures detonate: non-pawn pieces on adjacent squares are destroyed. Vaporize the enemy king to win — just not your own.',
  },
  {
    id: 'king-dash',
    name: 'King Dash',
    emoji: '⚡',
    description: 'The king may also dash two squares in a straight or diagonal line over an empty square.',
  },
];

function stepInto(state, r, c, color, dr, dc) {
  const nr = r + dr, nc = c + dc;
  if (!onBoard(nr, nc)) return null;
  const target = state.board[nr][nc];
  if (target && target.color === color) return null;
  return { from: { r, c }, to: { r: nr, c: nc }, capture: !!target };
}

MODS['royal-knights'] = {
  extraMoves(state, r, c, piece) {
    if (piece.type !== 'n') return [];
    const out = [];
    for (const [dr, dc] of AROUND) {
      const m = stepInto(state, r, c, piece.color, dr, dc);
      if (m) out.push(m);
    }
    return out;
  },
};

MODS['berserker-pawns'] = {
  extraMoves(state, r, c, piece, mode) {
    if (piece.type !== 'p') return [];
    const dir = piece.color === 'w' ? 1 : -1;
    const promoRank = piece.color === 'w' ? 7 : 0;
    const nr = r + dir;
    if (!onBoard(nr, c)) return [];
    const target = state.board[nr][c];
    // In attack mode the square ahead is always threatened; in move mode the
    // forward capture exists only when an enemy stands there (the plain
    // forward push is already generated by the base engine).
    if (mode === 'attacks' || (target && target.color !== piece.color)) {
      const m = { from: { r, c }, to: { r: nr, c }, capture: true };
      if (nr === promoRank) m.promotion = true;
      return [m];
    }
    return [];
  },
};

export const PORTALS = { d4: 'e5', e5: 'd4', e4: 'd5', d5: 'e4' };

MODS['wormholes'] = {
  priority: 1, // resolve teleport before anything that cares about the landing square
  afterApply(state, move) {
    const cur = move._finalTo || move.to;
    const exit = PORTALS[sq(cur.r, cur.c)];
    if (!exit) return;
    const { r, c } = coords(exit);
    if (state.board[r][c]) return; // occupied exit: portal fizzles, piece stays
    state.board[r][c] = state.board[cur.r][cur.c];
    state.board[cur.r][cur.c] = null;
    move._finalTo = { r, c };
  },
};

MODS['atomic-captures'] = {
  priority: 2, // detonate at the final landing square (post-teleport)
  afterApply(state, move, mover) {
    if (!move.capture) return;
    const cur = move._finalTo || move.to;
    for (const [dr, dc] of AROUND) {
      const r = cur.r + dr, c = cur.c + dc;
      if (!onBoard(r, c)) continue;
      const p = state.board[r][c];
      if (p && p.type !== 'p') {
        state.board[r][c] = null;
        state.captured[p.color === 'w' ? 'b' : 'w'].push(p.type);
      }
    }
  },
};

MODS['king-dash'] = {
  extraMoves(state, r, c, piece) {
    if (piece.type !== 'k') return [];
    const out = [];
    for (const [dr, dc] of AROUND) {
      const midR = r + dr, midC = c + dc;
      if (!onBoard(midR, midC) || state.board[midR][midC]) continue; // dash leaps an EMPTY square
      const m = stepInto(state, r, c, piece.color, 2 * dr, 2 * dc);
      if (m) out.push(m);
    }
    return out;
  },
};
